name: card_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.6.1
  get_it: ^7.7.0
  go_router: ^13.2.4
  google_mlkit_text_recognition: ^0.13.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  riverpod_annotation: ^2.3.5
  photo_view: ^0.15.0

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  path_provider: ^2.1.3
  # fpdart: ^1.1.0
  flutter_svg: ^2.0.10+1

  # freezed
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.4.0
  # freezed
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/data/
    - assets/data/user/
    - assets/data/settings/
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 100

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 100

    - family: Raleway-Italic
      fonts:
        - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-ExtraBoldItalic.ttf
          weight: 800
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/Raleway/Raleway-ThinItalic.ttf
          weight: 100
flutter_intl:
  enabled: true
